---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      # - JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - "${DATA_PATH}/jellyfin:/config"
      - "${MEDIA_PATH}:/data:ro"
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri

  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 1000:1000 # should be owner of volumes
    ports:
      - 4533:4533
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ""
    volumes:
      - "${DATA_PATH}/navidrome:/data"
      - "${MUSIC_PATH}:/music:ro"

  komga:
    image: gotson/komga
    container_name: komga
    volumes:
      - "${DATA_PATH}/komga:/config"
      - "${BOOKS_PATH}:/data:ro"
    ports:
      - 25600:25600
    user: "1000:1000"
    # remove the whole environment section if you don't need it
    environment:
      - TZ=${TZ}
    restart: unless-stopped

  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      # - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - "${DATA_PATH}/calibre_web:/config"
      - "${CALIBRE_LIBRARY_PATH}:/books"
    ports:
      - 8083:8083
    restart: unless-stopped
